# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cfd9339261d3d7c601f63ac7a3c0535cd1d7772ec8da1a82ed057de787171bd9c412a371b80dd562d90070ae41b65faaf81f7d8a88337e867885939f8b0bc9ad

test:
  secret_key_base: 48812734c7058b7e556b8f58f92fe98cea5f627a8c514e5d6dc0e7bccaf95d6510f769fb91bd153f9f363fa7d44b578cb4769aa1bc6a01acc58903e056ee53ba

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
